import { Field, InputType } from 'type-graphql';

/**
 * specify all the columns except the id column
 * because it is auto-generated by the database every time we insert a new row.
 */

@InputType() // For input type
export class UserInput {
    @Field({ nullable: false })
    email!: string;

    @Field({ nullable: false })
    firstName!: string;

    @Field({ nullable: false })
    lastName!: string;

    @Field({ nullable: true })
    password?: string;

    @Field({ nullable: true })
    picture?: string;

    @Field({ nullable: true })
    isSync?: boolean;
}

@InputType()
export class UserUpdateInput extends UserInput {
    @Field({ nullable: false })
    id: number;
}

@InputType()
export class UserUpdatePasswordInput extends UserInput {
    @Field({ nullable: false })
    oldPassword: string;

    @Field({ nullable: false })
    newPassword: string;
}
